"""Database backend adapter: SQLite (default, local-first) or PostgreSQL (hosted).

The stores were written against sqlite3 with ``?`` placeholders, ``sqlite3.Row``
rows and ``executescript`` for schema creation. This module keeps that surface
and adds a PostgreSQL implementation behind it, so the same store code runs
against a local SQLite file (the default, nothing leaves the machine) or a
PostgreSQL URL (the hosted deployment).

Select the backend with the value handed to the store:

* a filesystem path (``Path`` or ``str``) -> SQLite at that path
* ``postgres://`` / ``postgresql://`` URL -> PostgreSQL via psycopg 3

``REFORMULATION_DATABASE_URL`` is read by the app to pick the hosted backend.
"""
from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterable, Iterator, Sequence
import atexit
import hashlib
import os
import re
import sqlite3
import threading
import time

import numpy as np


def is_postgres_url(value: Any) -> bool:
    return isinstance(value, str) and value.lower().startswith(("postgres://", "postgresql://"))


def _coerce_param(value: Any) -> Any:
    """Make Python values acceptable to both drivers.

    SQLite is permissive; PostgreSQL types columns strictly. Booleans become
    ints (the schema stores flags as INTEGER), numpy scalars become Python
    scalars, and everything else passes through.
    """
    if isinstance(value, (bool, np.bool_)):
        return int(value)
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    return value


def _coerce_params(params: Any) -> Any:
    if params is None:
        return ()
    if isinstance(params, dict):
        return {key: _coerce_param(item) for key, item in params.items()}
    return tuple(_coerce_param(item) for item in params)


class Row(dict):
    """Row usable like ``sqlite3.Row``: by column name, by position, and as a dict."""

    __slots__ = ("_order",)

    def __init__(self, columns: Sequence[str], values: Sequence[Any]):
        super().__init__(zip(columns, values))
        self._order = tuple(values)

    def __getitem__(self, key):  # type: ignore[override]
        if isinstance(key, (int, slice)):
            return self._order[key]
        return super().__getitem__(key)

    def keys(self):  # sqlite3.Row exposes keys() too
        return super().keys()


_QMARK = re.compile(r"\?")


def _translate_sql(sql: str) -> str:
    """Translate the SQLite dialect used by the stores into PostgreSQL."""
    out = _QMARK.sub("%s", sql)
    out = out.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    out = out.replace("INSERT OR IGNORE INTO", "INSERT INTO")
    return out


class PostgresCursorResult:
    def __init__(self, cursor):
        self._cursor = cursor
        self._columns = [d.name for d in cursor.description] if cursor.description else []

    def _wrap(self, record):
        if record is None:
            return None
        return Row(self._columns, record)

    def fetchone(self):
        return self._wrap(self._cursor.fetchone())

    def fetchall(self):
        return [self._wrap(record) for record in self._cursor.fetchall()]

    def __iter__(self) -> Iterator[Row]:
        for record in self._cursor:
            yield self._wrap(record)

    @property
    def rowcount(self) -> int:
        return self._cursor.rowcount


class PostgresConnection:
    """psycopg 3 connection wrapped to look like the sqlite3 connection the stores expect."""

    backend = "postgres"

    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql: str, params: Any = ()) -> PostgresCursorResult:
        translated = _translate_sql(sql)
        if "INSERT OR IGNORE INTO" in sql:
            translated = translated.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
        cursor = self._raw.execute(translated, _coerce_params(params))
        return PostgresCursorResult(cursor)

    def executemany(self, sql: str, seq_of_params: Iterable[Any]) -> None:
        with self._raw.cursor() as cursor:
            cursor.executemany(_translate_sql(sql), [_coerce_params(p) for p in seq_of_params])

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            statement = statement.strip()
            if statement:
                self._raw.execute(_translate_sql(statement))

    def table_columns(self, table: str) -> set[str]:
        rows = self._raw.execute(
            "SELECT column_name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = %s",
            (table,),
        ).fetchall()
        return {row[0] for row in rows}

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


class SQLiteConnection:
    """Thin wrapper so both backends expose ``backend`` and ``table_columns``."""

    backend = "sqlite"

    def __init__(self, raw: sqlite3.Connection):
        self._raw = raw

    def execute(self, sql: str, params: Any = ()):
        return self._raw.execute(sql, _coerce_params(params))

    def executemany(self, sql: str, seq_of_params: Iterable[Any]) -> None:
        self._raw.executemany(sql, [_coerce_params(p) for p in seq_of_params])

    def executescript(self, script: str) -> None:
        self._raw.executescript(script)

    def table_columns(self, table: str) -> set[str]:
        return {row[1] for row in self._raw.execute(f"PRAGMA table_info({table})").fetchall()}

    def commit(self) -> None:
        self._raw.commit()

    def rollback(self) -> None:
        self._raw.rollback()

    def close(self) -> None:
        self._raw.close()


class _PostgresLink:
    """One server connection per database URL, shared by every store in the process.

    Opening a fresh TLS connection to a hosted database for every query would cost
    more than the query itself, so the connection is kept and reused. Access is
    serialized with a re-entrant lock (Streamlit runs each visitor's script in its
    own thread), and a connection that went away while idle (serverless databases
    suspend after a few minutes) is detected with a cheap ping and reopened.
    """

    PING_AFTER_SECONDS = 30.0

    def __init__(self, url: str):
        self.url = url
        self.lock = threading.RLock()
        self.raw: Any = None
        self.depth = 0
        self.last_ok = 0.0
        self.search_path: str | None = None

    def drop(self) -> None:
        raw, self.raw = self.raw, None
        self.search_path = None
        if raw is not None:
            try:
                raw.close()
            except Exception:  # noqa: BLE001 - already broken
                pass

    def _alive(self) -> bool:
        if self.raw is None or self.raw.closed:
            return False
        if time.monotonic() - self.last_ok < self.PING_AFTER_SECONDS:
            return True
        try:
            self.raw.execute("SELECT 1")
            self.raw.commit()
            self.last_ok = time.monotonic()
            return True
        except Exception:  # noqa: BLE001 - any failure means reconnect
            self.drop()
            return False

    def connection(self, schema: str | None):
        import psycopg  # imported lazily so local installs need no driver

        if not self._alive():
            # No server-side prepared statements: a long-lived connection would otherwise
            # keep plans that break when a table gains a column (or, in the test mode,
            # when search_path moves to another schema), and connection poolers such
            # as Neon's PgBouncer endpoint are happier without them.
            self.raw = psycopg.connect(self.url, prepare_threshold=None)
            self.search_path = None
            self.last_ok = time.monotonic()
        if schema != self.search_path:
            # SET is transactional: commit right away so a later rollback cannot undo it.
            if schema:
                self.raw.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
                self.raw.execute(f"SET search_path TO {schema}")
            else:
                self.raw.execute("SET search_path TO DEFAULT")
            self.raw.commit()
            self.search_path = schema
        return self.raw


_LINKS: dict[str, _PostgresLink] = {}
_LINKS_LOCK = threading.Lock()


def _link_for(url: str) -> _PostgresLink:
    with _LINKS_LOCK:
        link = _LINKS.get(url)
        if link is None:
            link = _LINKS[url] = _PostgresLink(url)
        return link


def _close_all_links() -> None:
    with _LINKS_LOCK:
        for link in _LINKS.values():
            with link.lock:
                link.drop()


atexit.register(_close_all_links)


class Database:
    """Opens connections for whichever backend the target describes.

    Test hook: when ``REFORMULATION_FORCE_DATABASE_URL`` is set, every store
    opened on a file path is redirected to that PostgreSQL URL, each path in
    its own schema, so the SQLite test suite runs unchanged against Postgres.
    """

    def __init__(self, target: str | Path):
        forced = os.environ.get("REFORMULATION_FORCE_DATABASE_URL", "")
        self.schema: str | None = None
        if is_postgres_url(target):
            self.backend = "postgres"
            self.url = str(target)
            self.path: Path | None = None
        elif forced and is_postgres_url(forced):
            self.backend = "postgres"
            self.url = forced
            self.path = None
            self.schema = "t_" + hashlib.sha1(str(Path(target).resolve()).encode()).hexdigest()[:12]
        else:
            self.backend = "sqlite"
            self.url = None
            self.path = Path(target)
            self.path.parent.mkdir(parents=True, exist_ok=True)

    @property
    def is_postgres(self) -> bool:
        return self.backend == "postgres"

    @contextmanager
    def connect(self):
        if self.is_postgres:
            yield from self._postgres_block()
            return
        raw = sqlite3.connect(self.path)
        raw.row_factory = sqlite3.Row
        raw.execute("PRAGMA foreign_keys = ON")
        con = SQLiteConnection(raw)
        try:
            yield con
            con.commit()
        except BaseException:
            con.rollback()
            raise
        finally:
            con.close()

    def _postgres_block(self):
        """One unit of work on the shared connection: commit at the outermost block."""
        link = _link_for(self.url)
        with link.lock:
            if link.depth and link.search_path != self.schema:
                raise RuntimeError("nested database work across two schemas on one connection")
            raw = link.connection(self.schema)
            con = PostgresConnection(raw)
            link.depth += 1
            try:
                yield con
                if link.depth == 1:
                    con.commit()
                    link.last_ok = time.monotonic()
            except BaseException:
                if link.depth == 1:
                    try:
                        con.rollback()
                    except Exception:  # noqa: BLE001 - connection is gone
                        link.drop()
                raise
            finally:
                link.depth -= 1

    def close(self) -> None:
        """Drop the shared server connection (SQLite opens per call, nothing to do)."""
        if self.is_postgres:
            link = _link_for(self.url)
            with link.lock:
                link.drop()

    def upsert_clause(self, conflict_columns: Sequence[str], update_columns: Sequence[str]) -> str:
        """``INSERT OR REPLACE`` replacement usable on both backends (append after VALUES (...))."""
        assignments = ", ".join(f"{column} = excluded.{column}" for column in update_columns)
        return f" ON CONFLICT({', '.join(conflict_columns)}) DO UPDATE SET {assignments}"
