"""v0.12: database backend adapter and self-serve workspaces (hosted tier)."""
from __future__ import annotations

from pathlib import Path
import os
import tempfile
import unittest

import numpy as np

from db_backend import Database, Row, _coerce_params, _translate_sql, is_postgres_url
from pilot_store import PilotStore


class BackendAdapterTest(unittest.TestCase):
    def test_backend_selection_by_target(self):
        self.assertTrue(is_postgres_url("postgresql://user@host/db"))
        self.assertTrue(is_postgres_url("postgres://user@host/db"))
        self.assertFalse(is_postgres_url("data/app.db"))
        self.assertFalse(is_postgres_url(Path("data/app.db")))

    def test_sql_translation_for_postgres(self):
        translated = _translate_sql(
            "CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT); "
            "INSERT OR IGNORE INTO t (name) VALUES (?)"
        )
        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", translated)
        self.assertNotIn("AUTOINCREMENT", translated)
        self.assertIn("INSERT INTO t (name) VALUES (%s)", translated)

    def test_parameter_coercion(self):
        self.assertEqual(_coerce_params((True, np.int64(3), np.float32(1.5), "x", None)), (1, 3, 1.5, "x", None))
        self.assertEqual(_coerce_params({"flag": np.bool_(False)}), {"flag": 0})

    def test_row_supports_name_index_and_dict_access(self):
        row = Row(["id", "name"], ["abc", "Lab"])
        self.assertEqual(row["name"], "Lab")
        self.assertEqual(row[0], "abc")
        self.assertEqual(list(row.keys()), ["id", "name"])
        self.assertEqual(dict(row), {"id": "abc", "name": "Lab"})

    def test_sqlite_database_round_trip(self):
        with tempfile.TemporaryDirectory() as tmp:
            database = Database(Path(tmp) / "nested" / "adapter.db")
            self.assertEqual(database.backend, "sqlite" if not os.environ.get("REFORMULATION_FORCE_DATABASE_URL") else "postgres")
            with database.connect() as con:
                con.executescript(
                    "CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT NOT NULL, flag INTEGER);"
                )
                con.execute("DELETE FROM items")
                con.execute("INSERT INTO items (label, flag) VALUES (?, ?)", ("first", True))
                con.executemany("INSERT INTO items (label, flag) VALUES (?, ?)", [("second", False), ("third", np.bool_(True))])
                rows = con.execute("SELECT label, flag FROM items ORDER BY id").fetchall()
                self.assertEqual([(r["label"], int(r["flag"])) for r in rows], [("first", 1), ("second", 0), ("third", 1)])
                self.assertEqual(rows[0][0], "first")
                self.assertEqual(con.table_columns("items"), {"id", "label", "flag"})


@unittest.skipUnless(os.environ.get("REFORMULATION_FORCE_DATABASE_URL"), "needs a PostgreSQL test database")
class SharedConnectionTest(unittest.TestCase):
    def test_connection_is_reused_and_revived_after_it_drops(self):
        import db_backend

        with tempfile.TemporaryDirectory() as tmp:
            store = PilotStore(Path(tmp) / "pilot.db")
            self.assertFalse(store.has_users())
            link = db_backend._link_for(store.database.url)
            first = link.raw
            self.assertFalse(store.has_users())
            self.assertIs(link.raw, first, "second unit of work should reuse the connection")

            # Server went away (serverless autosuspend, restart): the next block reconnects.
            first.close()
            self.assertFalse(store.has_users())
            self.assertIsNot(link.raw, first)

            # Idle long enough to ping: still one connection, still working.
            link.last_ok = 0.0
            store.register_owner(email="o@example.com", display_name="O", password="SecurePass123", organization_name="L")
            self.assertTrue(store.has_users())

    def test_failed_unit_of_work_rolls_back_and_connection_stays_usable(self):
        with tempfile.TemporaryDirectory() as tmp:
            store = PilotStore(Path(tmp) / "pilot.db")
            with self.assertRaises(Exception):
                with store.connection() as con:
                    con.execute("INSERT INTO organizations (id, name, created_at) VALUES (?, ?, ?)", ("org-1", "Lab", "now"))
                    con.execute("SELECT * FROM table_that_does_not_exist")
            with store.connection() as con:
                self.assertEqual(con.execute("SELECT COUNT(*) FROM organizations").fetchone()[0], 0)


class SelfServeWorkspaceTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.store = PilotStore(Path(self.tmp.name) / "pilot.db")
        self.owner, self.org = self.store.register_owner(
            email="owner@example.com", display_name="Owner", password="SecurePass123",
            organization_name="First Lab",
        )

    def tearDown(self):
        self.tmp.cleanup()

    def test_new_email_creates_a_separate_workspace(self):
        user_id, org_id = self.store.register_owner(
            email="instructor@example.com", display_name="Instructor", password="SecurePass123",
            organization_name="CHEM 3410",
        )
        self.assertNotEqual(user_id, self.owner)
        self.assertNotEqual(org_id, self.org)
        self.assertEqual(self.store.user_organizations(user_id)["name"].tolist(), ["CHEM 3410"])
        self.assertEqual(self.store.user_organizations(self.owner)["name"].tolist(), ["First Lab"])

    def test_existing_email_with_matching_password_adds_a_workspace(self):
        user_id, org_id = self.store.register_owner(
            email="owner@example.com", display_name="Owner", password="SecurePass123",
            organization_name="Second Lab",
        )
        self.assertEqual(user_id, self.owner)
        self.assertNotEqual(org_id, self.org)
        organizations = self.store.user_organizations(self.owner)
        self.assertEqual(organizations["name"].tolist(), ["First Lab", "Second Lab"])
        self.assertEqual(set(organizations["role"]), {"owner"})

    def test_existing_email_with_wrong_password_is_rejected_cleanly(self):
        with self.assertRaises(ValueError) as caught:
            self.store.register_owner(
                email="owner@example.com", display_name="Someone Else", password="Different123",
                organization_name="Hijack Lab",
            )
        self.assertIn("already exists", str(caught.exception))
        self.assertEqual(self.store.user_organizations(self.owner)["name"].tolist(), ["First Lab"])

    def test_repeated_failed_sign_ins_lock_the_email_then_clear_on_success(self):
        from product_store import MAX_FAILED_SIGN_INS, TooManyAttempts

        for _ in range(MAX_FAILED_SIGN_INS):
            self.assertIsNone(self.store.authenticate("owner@example.com", "wrong-password"))
        self.assertEqual(self.store.failed_sign_ins("owner@example.com"), MAX_FAILED_SIGN_INS)
        with self.assertRaises(TooManyAttempts):
            self.store.authenticate("owner@example.com", "SecurePass123")  # even the right password waits
        # Another account is unaffected.
        self.store.register_owner(
            email="other@example.com", display_name="Other", password="SecurePass123", organization_name="Other Lab"
        )
        self.assertIsNotNone(self.store.authenticate("other@example.com", "SecurePass123"))
        # Once the window has passed the account works again, and success clears the counter.
        with self.store.connection() as con:
            con.execute("UPDATE login_failures SET failed_at = ?", ("2000-01-01T00:00:00+00:00",))
        self.assertIsNotNone(self.store.authenticate("owner@example.com", "SecurePass123"))
        self.assertEqual(self.store.failed_sign_ins("owner@example.com"), 0)

    def test_weak_password_is_rejected_before_anything_is_written(self):
        with self.assertRaises(ValueError):
            self.store.register_owner(
                email="new@example.com", display_name="New", password="short",
                organization_name="New Lab",
            )
        self.assertIsNone(self.store.authenticate("new@example.com", "short"))


class SmtpSettingsTest(unittest.TestCase):
    def test_settings_come_from_any_reader_not_only_the_environment(self):
        from notifications import SMTPSettings

        values = {
            "REFORMULATION_SMTP_HOST": "smtp.example.com",
            "REFORMULATION_SMTP_PORT": "587",
            "REFORMULATION_SMTP_USERNAME": "mailer@example.com",
            "REFORMULATION_SMTP_PASSWORD": "app-password",
            "REFORMULATION_SMTP_TLS": "true",
            "REFORMULATION_EMAIL_FROM": "mailer@example.com",
        }
        settings = SMTPSettings.from_settings(lambda name: values.get(name, ""))
        self.assertEqual((settings.host, settings.port, settings.username, settings.sender, settings.use_tls),
                         ("smtp.example.com", 587, "mailer@example.com", "mailer@example.com", True))
        self.assertIsNone(SMTPSettings.from_settings(lambda name: ""))
        # Host without a sender (or the reverse) is not a usable configuration.
        self.assertIsNone(SMTPSettings.from_settings(lambda name: "smtp.example.com" if name.endswith("HOST") else ""))


if __name__ == "__main__":
    unittest.main()
